services:
    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus-1
        restart: unless-stopped
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - ./elasticsearch.rules.yml:/etc/prometheus/elasticsearch.rules.yml
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--web.enable-lifecycle'
        ports:
            - 9090:9090
        expose:
            - 9090
    node-exporter-1:
        image: prom/node-exporter:latest
        container_name: node-exporter-1
        restart: unless-stopped
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        command:
            - '--path.procfs=/host/proc'
            - '--path.rootfs=/rootfs'
            - '--path.sysfs=/host/sys'
            - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
        ports:
            - 9100:9100
        expose:
            - 9100
    grafana:
        image: "grafana/grafana-enterprise:10.2.0-ubuntu"
        container_name: grafana
        volumes:
            - ./config.ini:/etc/grafana/config.ini
            - ./provisioning:/etc/grafana/provisioning
            - ./dashboards:/var/lib/grafana/dashboards
        ports:
            - "3000:3000"
    elasticsearch-exporter:
        image: quay.io/prometheuscommunity/elasticsearch-exporter:latest
        container_name: elasticsearch-exporter
        command:
            - --es.uri=https://${ELASTIC_USER}:${ELASTIC_PASSWORD}@${ELASTIC_URL}
        restart: always
        ports:
            - "127.0.0.1:9114:9114"